#version: '2'
#services:
#  kafka:
#    image: spotify/kafka
#    ports:
#      - "2181:2181"
#      - "9092:9092"
#    environment:
#      ADVERTISED_HOST: localhost
#      ADVERTISED_PORT: 9092

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "test:1:3"
#    kafka2:
#      image: wurstmeister/kafka
#      ports:
#        - "9092:9093"
#      environment:
#        KAFKA_ADVERTISED_HOST_NAME: localhost:9093
#        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181